version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: dotnet tool install --global PowerShell --version 6.0.0
      - run: pwsh ./scripts/test1.ps1
      - run: 
         command: echo "This is a bash output"
         shell: bash.exe
      - run:
         command: echo "This is a command output"
         shell: cmd.exe
      - run:
          name: "Generate Dummy artifacts"
          command: | 
           mkdir -p /tmp/dummy_dumps
           cp /artifacts/*.html /tmp/dummy_dumps
      - store_artifacts:
          path: /tmp/dummy_dumps